/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hangmanprojectv1;
import java.util.Random;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


/**
 *
 * @author tony
 */
public class Buttons extends javax.swing.JFrame {
    
    /**
     * Creates new form Buttons
     */
    int[] locationArray;
    
    Color red = new Color(255,0,0);
    Color  green   = new Color(0, 255,  0);
    Color  blue   = new Color(0, 0, 255);
    Color purple = new Color(200, 0, 255);
    Color yellow = new Color(255, 255, 0);
    Color chosenColor; 
    
    JButton[] buttonArray = new JButton[16];
    
    int location1;//blue
    int location2;//red
    int location3;//yellow
    int location4;//green
    int location5;//purple
    
    String chosenWord;//selected color
    
    public Buttons() {
        initComponents();
        jButton0.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton10.setVisible(false);
        jButton11.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jButton14.setVisible(false);
        jButton15.setVisible(false);
        
        buttonArray[0]= jButton0;
        buttonArray[1]= jButton1;
        buttonArray[2]= jButton2;
        buttonArray[3]= jButton3;
        buttonArray[4]= jButton4;
        buttonArray[5]= jButton5;
        buttonArray[6]= jButton6;
        buttonArray[7]= jButton7;
        buttonArray[8]= jButton8;
        buttonArray[9]= jButton9;
        buttonArray[10]= jButton10;
        buttonArray[11]= jButton11;
        buttonArray[12]= jButton12;
        buttonArray[13]= jButton13;
        buttonArray[14]= jButton14;
        buttonArray[15]= jButton15;
        
        locationArray = buttonDecision();
        
        location1= locationArray[0];
        location2 = locationArray[1];
        location3 = locationArray[2];
        location4 = locationArray[3];
        location5 = locationArray[4];
        
        buttonArray[location1].setVisible(true);
        buttonArray[location2].setVisible(true);
        buttonArray[location3].setVisible(true);
        buttonArray[location4].setVisible(true);
        buttonArray[location5].setVisible(true);
        
        chosenWord = randomWord();
        jLabel2.setText(chosenWord);
        
        chosenColor=randomColor();
        jLabel2.setForeground(chosenColor);
        jLabel2.setFont(new Font("Serif",Font.BOLD,20));
        
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("TIME");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COLOR");

        jPanel2.setLayout(new java.awt.GridLayout(4, 4, 5, 5));

        jButton0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton0MouseExited(evt);
            }
        });
        jPanel2.add(jButton0);
        jPanel2.add(jButton1);
        jPanel2.add(jButton2);
        jPanel2.add(jButton3);
        jPanel2.add(jButton4);
        jPanel2.add(jButton5);
        jPanel2.add(jButton6);
        jPanel2.add(jButton7);
        jPanel2.add(jButton8);
        jPanel2.add(jButton9);
        jPanel2.add(jButton10);
        jPanel2.add(jButton11);
        jPanel2.add(jButton12);
        jPanel2.add(jButton13);
        jPanel2.add(jButton14);
        jPanel2.add(jButton15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 373, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 73, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      private int[] buttonDecision()
      {
          int[] locations = new int[5];
          int l1;
          int l2;
          int l3;
          int l4;
          int l5;
          Random rand = new Random();
          l1 = rand.nextInt(16); 
          buttonArray[l1].setBackground(blue);
          
          l2 = rand.nextInt(16);
          if(l2==l1)
          {
              l2=rand.nextInt(16);
          }
          buttonArray[l2].setBackground(red);
          l3 = rand.nextInt(16);
          if(l3==l1 || l3==l2)
          {
              l3=rand.nextInt(16);
          }
          buttonArray[l3].setBackground(yellow);
          l4 = rand.nextInt(16);
          if(l4==l1 || l4==l2 || l4 == l3)
          {
              l4= rand.nextInt(16);
          }
          buttonArray[l4].setBackground(green);
          l5 = rand.nextInt(16);
          if(l5==l1 || l5==l2 || l5 == l3 || l5==l4)
          {
              l5= rand.nextInt(16);
          }
          buttonArray[l5].setBackground(purple);
          
          locations[0]= l1;
          locations[1]= l2;
          locations[2]= l3;
          locations[3]= l4;
          locations[4]= l5;
          return locations;
      }
      public String randomWord()
      {
        Random rand = new Random();
        String[] words = new String[5];
        words[0] = "BLUE";
        words[1] = "RED";
        words[2] = "YELLOW";
        words[3] = "GREEN";
        words[4] = "PURPLE";
        
        int choose = rand.nextInt(5);
        return words[choose];
      }
      
      public Color randomColor()
      {
          Random rand = new Random();
          Color[] color = new Color[5];
          color[0] = new Color(255,0,0);//red
          color[1]  = new Color(0, 255,  0);//green
          color[2]  = new Color(0, 0, 255);//blue
          color[3] = new Color(200, 0, 255);//purple
          color[4] = new Color(255, 255, 0);//yelow
          
          int choose = rand.nextInt(5);
          return color[choose];
         
          
      }
      
    private void jButton0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton0MouseEntered
        // TODO add your handling code here:
        
          jButton0.setBorder(BorderFactory.createLineBorder(Color.black,3));
        
    }//GEN-LAST:event_jButton0MouseEntered

    private void jButton0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton0MouseExited
        // TODO add your handling code here:
       
         jButton0.setBorderPainted(false);
        
    }//GEN-LAST:event_jButton0MouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buttons().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
